#!/usr/bin/env bash
#
# setup_clausecker_lemire.sh -- build the Clausecker-Lemire (simdutf) UTF-16
# validation baseline.
#
#     ./scripts/setup_clausecker_lemire.sh
#
# Fetches simdutf at a pinned commit into .deps/simdutf (git-ignored, never
# committed), generates its single-header amalgamation, and compiles our wrapper
# external/baselines/clausecker_lemire/utf16validate_cl.cpp against it.
#
# Nothing from simdutf is vendored into this repository. See
# external/baselines/clausecker_lemire/README.md for attribution and licensing.
#
# Environment overrides (all optional):
#     SIMDUTF_DIR=/path        where to place the simdutf checkout
#     SIMDUTF_REMOTE=<url>     clone source (default: the upstream GitHub repo)
#     CXX=/path/to/c++         compiler to use
#
# This script never installs packages and never runs a destructive git reset.

set -euo pipefail

# --- Pinned upstream (mirrored in the baseline README) -------------------------
SIMDUTF_REMOTE_DEFAULT="https://github.com/simdutf/simdutf.git"
SIMDUTF_TAG="v9.0.0"
SIMDUTF_COMMIT="ca7acbcea967b5dcbab490066e99e3a6e6925539"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

SIMDUTF_REMOTE="${SIMDUTF_REMOTE:-$SIMDUTF_REMOTE_DEFAULT}"
SIMDUTF_DIR="${SIMDUTF_DIR:-$REPO_ROOT/.deps/simdutf}"
BIN_DIR="$REPO_ROOT/.deps/baselines/bin"
WRAPPER="$REPO_ROOT/external/baselines/clausecker_lemire/utf16validate_cl.cpp"
BIN="$BIN_DIR/utf16validate_cl"

err()  { echo "ERROR: $*" >&2; exit 1; }
info() { echo "==> $*"; }

for tool in git python3; do
    command -v "$tool" >/dev/null 2>&1 \
        || err "'$tool' not found in PATH. Please install it. (This script does not install packages.)"
done
CXX_BIN="${CXX:-$(command -v c++ || true)}"
[ -n "$CXX_BIN" ] || err "no C++ compiler found; set CXX=/path/to/c++"
[ -f "$WRAPPER" ] || err "wrapper source not found: $WRAPPER"

# --- Fetch the pinned upstream -------------------------------------------------
if [ ! -d "$SIMDUTF_DIR/.git" ]; then
    info "Cloning simdutf $SIMDUTF_TAG into $SIMDUTF_DIR"
    mkdir -p "$(dirname "$SIMDUTF_DIR")"
    git clone --quiet --depth 1 --branch "$SIMDUTF_TAG" "$SIMDUTF_REMOTE" "$SIMDUTF_DIR"
else
    info "Reusing existing simdutf checkout: $SIMDUTF_DIR"
fi

HAVE="$(git -C "$SIMDUTF_DIR" rev-parse HEAD)"
if [ "$HAVE" != "$SIMDUTF_COMMIT" ]; then
    err "simdutf checkout is at $HAVE but this project pins $SIMDUTF_COMMIT ($SIMDUTF_TAG).
  Remove it and re-run:  rm -rf \"$SIMDUTF_DIR\""
fi
info "simdutf pinned at $SIMDUTF_COMMIT ($SIMDUTF_TAG)"

# --- Single-header amalgamation (generated by upstream's own script) -----------
HEADER="$SIMDUTF_DIR/singleheader/simdutf.h"
SOURCE="$SIMDUTF_DIR/singleheader/simdutf.cpp"
if [ ! -f "$HEADER" ] || [ ! -f "$SOURCE" ]; then
    info "Generating simdutf single-header amalgamation"
    ( cd "$SIMDUTF_DIR" && python3 singleheader/amalgamate.py >/dev/null )
fi
[ -f "$HEADER" ] && [ -f "$SOURCE" ] \
    || err "amalgamation did not produce $HEADER / $SOURCE"

# --- Build the wrapper ---------------------------------------------------------
mkdir -p "$BIN_DIR"
info "Building utf16validate_cl with $CXX_BIN"
"$CXX_BIN" -O3 -std=c++17 \
    -I "$SIMDUTF_DIR/singleheader" \
    "$WRAPPER" "$SOURCE" \
    -o "$BIN"

[ -x "$BIN" ] || err "build finished but $BIN is missing"

echo
info "Baseline ready."
echo "    Binary         : $BIN"
echo "    Implementation : $("$BIN" --impl | sed 's/^simdutf implementation = //')"
echo "    Usage          : $BIN <file.bin>"
